spring:
  cloud:
    stream:
      bindings:
        input:
          destination: wdtest_
          content-type: application/json
          group: average
  rabbitmq:
    host: 192.168.0.128
    port: 5672
    username: root
    password: root

    virtual-host: my_vhost
logging:
  config: classpath:conf/log4j2-dev.xml