spring:
  application:
    name: eureka-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 2102
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

