spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/endermeihl/config-repo-demo.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 1201
